### ISSUE TITLE
New harmonyhubjs-client but nevertheless MAX_CLIENTS=6 ERROR

### ISSUE THREAD

**Issue by m4d-maNu** [swissmanu/harmonyhubjs-client#44] opened 2018-09-11 07:58 UTC
Hi,
I downloaded the harmonyhubjs-client and replace the old from homebridge-harmonyhub, but the MAX_CLIENTS=6 ERROR come again.

I see here on git this example for the settings, but i can`t fing the default settings... Can anyone help me? Where is the location from the default settings, that i can change the ip.

**Comment by swissmanu** [comment] 2018-12-06 07:41
duplicate of #34

**Closed by swissmanu** 2018-12-06 07:41 UTC
Labels: duplicate
